KlimaDAO/klima-subgraph

lib/utils/Constants.ts, protocol-metrics/generated/schema.ts, protocol-metrics/schema.graphql, protocol-metrics/src/sKlimaV1.ts, protocol-metrics/src/utils/Epoch.ts, protocol-metrics/src/utils/ProtocolMetrics.ts
Added dynamic rebase logic within Epoch.ts
It takes average duration of last X epochs as a dynamic rebase value
=> Dynamic rebase rate

lib/tokens/TokenFactory.ts, lib/tokens/impl/NCT.ts
Add NCT to both token implementations and `TokenFactory`
=> Add NCT to token implementations

protocol-metrics/generated/schema.ts, protocol-metrics/schema.graphql, protocol-metrics/src/utils/ProtocolMetrics.ts
Added:
- TotalKlimaInLP
- TotalKlimaUnstaked
=> Token state protocol metrics

protocol-metrics/generated/schema.ts, protocol-metrics/schema.graphql, protocol-metrics/src/utils/ProtocolMetrics.ts
Added USDC fields in protocol metrics:
- treasuryUSDCInLP
- treausuryBalanceUSDC
- daoBalanceUSDC
- daoBalanceKLIMA
https://ibb.co/qWK028P
=> Treasury and DAO USDC fields in protocol metrics

protocol-metrics/src/utils/ProtocolMetrics.ts
=> Add marked down LP calculation for carbon custodied

protocol-metrics/src/utils/ProtocolMetrics.ts
Added USDC treasury asset tracking (within TreasuryAsset entity) within Protocol Metrics subgraph.
Subgraph [url](https://api.thegraph.com/subgraphs/name/milos1991/klimaprotocol/graphql?query=query+MyQuery+%7B%0A++treasuryAssets%28orderBy%3A+timestamp%2C+orderDirection%3A+desc%2C+where%3A+%7Btoken%3A+%220x2791Bca1f2de4661ED88A30C99A7a9449Aa84174%22%7D%29+%7B%0A++++id%0A++++token%0A++++timestamp%0A++++marketValue%0A++++tokenBalance%0A++%7D%0A%7D)
Screenshot:
=> usdc-treasury-asset: Added usdc tracking

pairs/generated/BCT_USDC/UniswapV2Pair.ts, pairs/generated/KLIMA_BCT/Pair.ts, pairs/generated/KLIMA_BCT/UniswapV2Pair.ts, pairs/generated/KLIMA_MCO2/Pair.ts, pairs/generated/KLIMA_MCO2/UniswapV2Pair.ts, pairs/generated/KLIMA_NBO/Pair.ts, pairs/generated/KLIMA_NBO/TridentPair.ts, pairs/generated/KLIMA_NBO/UniswapV2Pair.ts, pairs/generated/KLIMA_UBO/Pair.ts, pairs/generated/KLIMA_UBO/TridentPair.ts, pairs/generated/KLIMA_UBO/UniswapV2Pair.ts, pairs/generated/KLIMA_USDC/Pair.ts, pairs/generated/KLIMA_USDC/UniswapV2Pair.ts, pairs/generated/NCT_USDC/Pair.ts, pairs/generated/NCT_USDC/UniswapV2Pair.ts, pairs/generated/schema.ts, pairs/src/MCO2Pair.ts, pairs/src/Pair.ts, pairs/src/TridentPair.ts, pairs/subgraph.yaml
In this PR, I have:
Added the following methodology: Change prices when KLIMA/USDC price change
Working example: https://thegraph.com/hosted-service/subgraph/originalpkbims/klimapairs-price-test
=> Added following methodology: Change prices when KLIMA/USDC price change

.github/workflows/deploy.yaml
=> Fix deployment logic for carbon subgraphs

polygon-bridged-carbon/src/KlimaRetirementAggregator.ts, polygon-bridged-carbon/src/utils/Token.ts
=> Fix handling of token field for V2 retirements

ethereum-bridged-carbon/src/MossCarbon.ts, ethereum-bridged-carbon/subgraph.yaml, lib/abis/MossCarbonInventoryControl.json
=> Populate missing fields for Moss retires

carbonmark/src/Entities.ts
extract registry name from `Projects` array
=> Extract registry name

polygon-digital-carbon/src/utils/MethodologyCategories.ts
=> Add missing ICR methodologies to categorization

carbonmark/schema.graphql, carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts, carbonmark/subgraph.yaml
Add the token symbol to the Listing type
=> Carbonmark: add tokenSymbol to Listing

lib/utils/Constants.ts, protocol-metrics/schema.graphql, protocol-metrics/src/utils/ProtocolMetrics.ts
=> Add missing LPs and KLIMA to treasury assets

polygon-bridged-carbon/src/utils/MethodologyCategories.ts
This drifted from the other mapping
=> Fix meth cat

carbonmark/src/Projects.ts, carbonmark/src/scripts/updateICRProjects.ts
Not all projects were added to the most recent deployment I believe
=> Add all ICR projects to main

carbonmark/schema.graphql, carbonmark/src/Carbonmark.ts, carbonmark/subgraph.yaml
Added an activity, `updatedExpiration`, for when the price or amount does not change.
Only price or amount changes were being caught previously.
=> Carbonmark- Add UpdatedExpiration Activity

lib/tokens/impl/CCO2.ts, lib/utils/Constants.ts, lib/utils/Price.ts, pairs/src/Pair.ts, pairs/subgraph.yaml, protocol-metrics/src/utils/ProtocolMetrics.ts
Now that pool is launched we should capture these metrics
=> Add CCO2 to pairs subgraph and treasury assets

lib/utils/Constants.ts, lib/utils/Decimals.ts, polygon-digital-carbon/package.json, polygon-digital-carbon/src/RetirementHandler.ts, polygon-digital-carbon/src/TransferHandler.ts, polygon-digital-carbon/src/sKlimaV1.ts, polygon-digital-carbon/src/utils/CarbonCreditSnapshot.ts, polygon-digital-carbon/subgraph.yaml, yarn.lock
ICR adjusted the number of decimals used for credits from 0 to 18. This should adjust the decimals prior to the migration
=> Digital Carbon - ICR Decimal Adjustment

.github/workflows/deploy.yaml
DO NOT MERGE UNTIL ALL SUBGRAPHS ARE UPGRADED!
=> Switch to subgraph studio deployment logic

polygon-digital-carbon/schema.graphql, polygon-digital-carbon/src/utils/CarbonCredit.ts, polygon-digital-carbon/subgraph.yaml
Add enum and token update values for J-Credits
=> Hotfix for Initial J-Credits

carbonmark/src/Projects.ts
Incorrect vintage for J-credit test project, fixed.
=> Fix vintage for J-credit test Project

polygon-digital-carbon/src/utils/MethodologyCategories.ts
=> Add missing category mappings

carbonmark/src/Projects.ts, lib/utils/ICRProjectInfo.ts
Added early test projects (just in case) as well as a new mangrove project from Saudia Arabia to both digital-carbon and the marketplace.
=> Marketplace and Digital Carbon: Add new ICR project and fix case for existing project

polygon-digital-carbon/schema.graphql, polygon-digital-carbon/src/MetadataHandler.ts
Syncs have been broken because of type mismatch. This PR improves handling the types returned from ipfs. Test deployment syncing.
=> [`digital-carbon`] Improved handling of types in retrieving ipfs data

carbonmark/package.json, carbonmark/src/Entities.ts
=> test merge

.github/workflows/deploy.yaml, carbonmark/src/Carbonmark.ts
=> Test with explicit git add

.github/workflows/deploy.yaml, carbonmark/package.json, carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> corrected path

carbonmark/package.json, carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> rebase additiong

carbonmark/package.json, carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> add missing pdc version.ts file

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> Test merge branch

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> max-parallel depth of one with correct indentation

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> modify commit for only commit if changes

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> Testing PR description scraping

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> Test for initial deploy of versioned subgraph case

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> Fix JS comment syntax

.github/workflows/deploy.yaml, carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> change github to octokit

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> new octokit script

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> replace octokit with github 

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
=> tsconfig for imports

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
feat: fix tsconfig for esModuleInterop
=> feat: fix tsconfig for esModuleInterop

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
feat: install octokit at rookt in deploy yaml
=> install octokit at rookt in deploy yaml

carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
feat: throw error if commits but no changelog detected
=> throw error if commits but no changelog detected

polygon-digital-carbon/package.json, polygon-digital-carbon/src/KlimaAggregator.ts
The pdc version handler was incorrectly assigning versions to the version entity
fix: change pdc schema and published version to utils/version
=> Fix PDC version handler to schema and published version

.github/workflows/deploy.yaml
Remove unused `VERSIONED_SUBGRAPHS` check
fix: fix deploy action through unused versioned_subgraphs check
=> [`actions`] Remove `VERSIONED_SUBGRAPHS` check

.github/workflows/deploy.yaml
Remove trailing parentheses from conditional check
fix: removed extra parentheses from alchemy conditional
=> [`actions`] Remove trailing parentheses

polygon-digital-carbon/package.json, polygon-digital-carbon/schema.graphql
One line change to prevent subgraph breaking when we deploy RA upgrade and start retiring CMARK credits
- `chore(polygon-digital-carbon): add CMARK registry to enum to prevent breakage`
=> Add CMARK registry to prevent breakages

polygon-digital-carbon/package.json, polygon-digital-carbon/src/RetirementHandler.ts
Clean up redundant logic whenc creating cco2 `Project` entity
fix: clean up cco2 handler logic
=> [`PDC`] Refactor cco2 handler

.github/pull_request_template.md, polygon-digital-carbon/package.json, polygon-digital-carbon/subgraph.template.yaml
Fixing drift that should have been avoided and adding a note to future self to PR checklist
=> Reconcile drift in subgraph template and add note to PR checklist

.github/workflows/deploy.yaml
chore: fix gha deployment permissions
=> Fix deployment commits

carbonmark/package.json, carbonmark/schema.graphql, carbonmark/src/Carbonmark.ts, carbonmark/src/Entities.ts
Two issues fixed:
1. not all activities were being assigned a listing
2. a changed min fill amount, in this case from a diamondCut update, were not being tracked by the ListingUpdated handler
fix: marketplace activities now handle changed minFillAmounts
=> [`Carbonmark`] Fix marketplace activities

carbonmark/package.json, carbonmark/src/Projects.ts, lib/utils/CMARKProjectInfo.ts, pairs/package.json, polygon-bridged-carbon/package.json, polygon-digital-carbon/package.json, user-carbon/package.json
- Fixes CMARK project info
- `feat: add project info for CMARK-0`
- `fix: country info for CMARK-1`
=> Fix CMARK project info

carbonmark/package.json, carbonmark/src/Carbonmark.ts
- `fix: the listing not being saved when handling listingUpdated event`
=> Fix handle listing updated

carbonmark/package.json, lib/utils/TVERProjectInfo.ts, makefile, package-lock.json, pairs/package.json, polygon-bridged-carbon/package.json, polygon-digital-carbon/networkConfig/localhost.json, polygon-digital-carbon/networkConfig/matic.json, polygon-digital-carbon/package.json, polygon-digital-carbon/schema.graphql, polygon-digital-carbon/src/templates/CarbonmarkCreditTokenFactory.ts, polygon-digital-carbon/src/utils/CarbonCredit.ts, polygon-digital-carbon/src/utils/CarbonProject.ts, polygon-digital-carbon/subgraph.template.yaml, polygon-digital-carbon/subgraph.yaml, polygon-digital-carbon/tests/TVER.test.ts, user-carbon/package.json
* Initial TVER registry support
* Increment carbonmark version
* Add TVER test
* Fix logic for bridge
* Add missing version bumps
* Add proper prefix unpacking logic
=> Add TVER registry (#383)

carbonmark/package.json, carbonmark/src/Projects.ts, lib/utils/TVERProjectInfo.ts, pairs/package.json, polygon-bridged-carbon/package.json, polygon-digital-carbon/package.json, user-carbon/package.json
Add TVER-0 and TVER-40
NOTE: Can't currently find deployed TVER-40 address
chore: add TVER-0 and TVER-40 project info
=> Add TVER-0 and TVER-40 Project Info

carbonmark/package.json, carbonmark/src/Projects.ts, lib/utils/TVERProjectInfo.ts, pairs/package.json, polygon-bridged-carbon/package.json, polygon-digital-carbon/package.json, user-carbon/package.json
Add TVER-0 and TVER-40
chore: add tver-0 and tver-40
=> Add TVER Projects

carbonmark/package.json, carbonmark/src/Projects.ts, lib/utils/TVERProjectInfo.ts, pairs/package.json, polygon-bridged-carbon/package.json, polygon-digital-carbon/package.json, user-carbon/package.json
chore: carbonmark 1.6.7 and pdc 1.5.2 TVER projects
=> Deployments (update TVER projects)

carbonmark/package.json, carbonmark/src/Projects.ts, lib/utils/CMARKProjectInfo.ts, pairs/package.json, polygon-bridged-carbon/package.json, polygon-digital-carbon/package.json, user-carbon/package.json
l## 📄 Description
chore: add CMARK-2
=> Add CMARK-2

carbonmark/package.json, carbonmark/src/Projects.ts, lib/utils/CMARKProjectInfo.ts, pairs/package.json, polygon-bridged-carbon/package.json, polygon-digital-carbon/package.json, user-carbon/package.json
=> Add CMARK-2 (Deployments)

carbonmark/package.json, carbonmark/src/Projects.ts
=> Add missing contract addr for TVER-40

carbonmark/src/Projects.ts, pairs/package.json, polygon-bridged-carbon/package.json, polygon-digital-carbon/package.json, user-carbon/package.json
chore: update addresses and methodologies for TVER-40 and CMARK-2
=> Update Marketplac for TVER-40 and CMARK-2 issuances

carbonmark/package.json, carbonmark/src/Entities.ts, carbonmark/src/Projects.ts
chore: fix TVER-40 address casing and cast address comparison toLowerCase() for project info addresses
=> Fix TVER-40 address casing

package-lock.json, polygon-digital-carbon/package.json
=> Reploy main

.github/actions-scripts/generateChangelog.mjs, .github/workflows/check-version.yaml, .github/workflows/ci.yaml
* Provide authenticated token to run tests in CI
* Return empty array for no changelog
fix: return empty array for no changelog
=> [`GHA`] Further adjustments

pairs/package.json, pairs/version.json
Increment version to v1.1.2 to trigger a new build because v1.1.1 did not deploy on alchemy
=> chore(pairs): v1.1.2
