polygon-bridged-carbon/src/ToucanCarbonOffsets.ts
polygon-bridged-carbon/src/utils/CarbonMetrics.ts
polygon-bridged-carbon/src/utils/CarbonOffsets.ts
polygon-bridged-carbon/subgraph.yaml

- Remove assumption that TCO2s sent to the zero address are always retired
- Fix missing entity values on creation
This is merged to staging and the indexed deployment can be found here: https://api.thegraph.com/subgraphs/name/cujowolf/polygon-bridged-carbon-dev
These changes have also been incorporated into the staging deployment of the carbon dashboard for additional verificaiton.

Use `Retired` event for Toucan retirements

---

lib/abis/ToucanCarbonOffsets_1.4.0.json
polygon-bridged-carbon/src/ToucanCarbonOffsets.ts
polygon-bridged-carbon/subgraph.yaml

Version 1.4.0 of the TCO2 contract introduced a new `Retired` event signature.
This adds both the full abi for version 1.4.0 of the TCO2 implementation, as well as adding the new signature to a combined abi for use in a common subgraph template.
Fully indexed staged deployment can be found here: https://api.thegraph.com/subgraphs/id/QmPw7ch26mmSQSncbaBq6NAu8btraFGkmmfMddb8NqLHQE
Using this query against the current deployment, you can see that the correct `totalRetired` is now populated with 12.5 rather than zero.
```
query MyQuery {
carbonOffsets(where: {projectID: "VCS-1764"}) {
id
vintageYear
totalRetired
totalBridged
}
}
```

Add additional retirement event signature to TCO2s

---

.github/workflows/deploy.yaml

Resolves warning about `set-output` being deprecated using new logic defined in https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Switch to updated GitHub Actions logic for storing output

---

ethereum-bridged-carbon/src/MossCarbon.ts

I think this duplicate logic is resulting in null offset entities, which then breaks queries like this

Fix null offset entities

---

carbonmark/src/Carbonmark.ts

Fix bad handler assumption that a listed token is an ERC20 and has the symbol method available.

Catch reverts on calling listing token for symbol

---

lib/utils/Dates.ts
polygon-digital-carbon/src/utils/CarbonCredit.ts
polygon-digital-carbon/subgraph.yaml

Originally the integer used to represent the vintage of a credit was converted to an i32. This caused and overflow and incorrect reporting of vintages issues past 2038.

Digtal Carbon - Vintage Calculation

---

.gitignore
polygon-digital-carbon/schema.graphql
polygon-digital-carbon/src/KlimaAggregator.ts
polygon-digital-carbon/src/RetirementHandler.ts
polygon-digital-carbon/src/TransferHandler.ts
polygon-digital-carbon/src/utils/Provenance.ts
polygon-digital-carbon/src/utils/Retire.ts
polygon-digital-carbon/subgraph.yaml

Ensure consistency between all retirement IDs being created to use the `tx.from` address. Additionally use all transfer events to create any needed provenance records, then flag the latest as a retirement if a retirement happened in the same transaction hash.
Small generalization for gitignore.

Digital Carbon - Retirement ID update

---

carbonmark/schema.graphql
carbonmark/src/Carbonmark.ts
carbonmark/src/Entities.ts

With ICR listings include the tokenId of the `Listing` entity for querying the details of a listing.

Carbonmark: Add tokenId to Listing Entity

---

carbonmark/schema.graphql
carbonmark/src/Carbonmark.ts
carbonmark/src/Entities.ts
carbonmark/subgraph.yaml

Added a tokenStandard field for a more reliable way to check the token type (in case future non-ICR 1155s have zero index tokenIds).
Also added a token symbol for 1155s in `registry-registryId-vintage` format.

tokenstandard + symbol

---

polygon-digital-carbon/src/templates/ICRCarbonContractRegistry.ts

Changes the ICR projectIds to the regular registry-registryNum format.
test deployment: https://api.thegraph.com/subgraphs/id/QmSLBeufcG3XUUXbh1bAXYzNdykMCb2WHmDW56Z3DXR78Q

Formating ICR projectId to `registry-registryNum` format

---

carbonmark/src/Carbonmark.ts

The frontend was getting a contract error as the min fill had been updated and a retire attempt below current minFill but above the original was reverting.

Update minFill amount in `handleListingUpdated`

---

carbonmark/src/Carbonmark.ts
carbonmark/src/Entities.ts
lib/utils/Constants.ts
lib/utils/Decimals.ts

Historical amounts, all for inactive listings, are handled conditionally prior to a block after the ICR migration and before any further listings.
current deployment: https://thegraph.com/hosted-service/subgraph/psparacino/carbonmark--testing-only

Adjust Historical Activity Amounts to Reflect ICR migration

---

carbonmark/schema.graphql
carbonmark/src/Carbonmark.ts
carbonmark/src/Entities.ts
carbonmark/src/Projects.ts
carbonmark/src/scripts/updateTokenIds.ts

Fixing the marketplace ICR vintages bug-->
Before `loadOrCreateProject` would only check the address as every ERC20 followed that pattern, but for ICR tokens it would create a project with the first ICR project with that address found i.e. it would always create the project with the oldest vintage.
Updated a script to retrieve tokenIds and assign to `PROJECT_INFO`.
Added `tokenId` to the Project entity.
This could be more robust, both of which I think can be rolled into the Project Info upgrade: 
1) Tokens i.e. they're not going to have over 1000 exPosts and ExAntes any time soon but the `fetchTokenIds` requests should make sure it retrieves all tokens and tokenIds if > 1000.
2) The updateICRMainnet projects also uses a deprecated API and needs to be updated to use the new endpoint and …

Marketplace/ICR Vintages Fix

---

carbonmark/networkConfig/matic.json
carbonmark/networkConfig/mumbai.json
carbonmark/package.json
carbonmark/subgraph.template.yaml
package.json
polygon-digital-carbon/networkConfig/matic.json
polygon-digital-carbon/networkConfig/mumbai.json
polygon-digital-carbon/package.json
polygon-digital-carbon/subgraph.template.yaml
polygon-digital-carbon/subgraph.yaml
yarn.lock

Templating for pdc and carbonmark polygon and mumbai. This will make it quick to add amoy as well when mumbai is deprecated.
Couldn't find addresses for most of the Toucan mumbai contracts, but not sure that's a a high priority issue. The block numbers for mumbai are also geared towards testing the jcredit subgraph and so are probably not accurate for general purpose testing.

Carbonmark and PDC manifest network templates

---

polygon-digital-carbon/schema.graphql
polygon-digital-carbon/src/utils/Token.ts
polygon-digital-carbon/subgraph.yaml

With this change we should be able to remove the ICR subgraph dependency in the api.

`polygon-digital-carbon` : Add isExAnte field to `Token` entity

---

carbonmark/src/Projects.ts

This PR adds currently minted ECO and J credit projects to the marketplace.
Digital carbon doesn't need additional info in lib for c3 projects as c3 includes all of this info onchain with getProjectInfo() on the token contract.

[Carbonmark] Add tokenized `ECO_REGISTRY` and `J_CREDIT` projects to marketplace

---

polygon-digital-carbon/src/utils/Holding.ts

This query:
```graphql
{
holdings {
account {
id
}
}
}
```
is broken on the production subgraph with null error for an account. This PR ensures every account with a holding has an `Account` created for it.

create account for all holdings

---

polygon-digital-carbon/schema.graphql
polygon-digital-carbon/src/templates/C3ProjectTokenFactory.ts
polygon-digital-carbon/src/utils/C3.ts
polygon-digital-carbon/utils/getRetirementsContractAddress.ts

Use `Bytes` for the C3RetireRequest id instead of ID/string to improve performance and sync speed
test deployment (still syncing): https://api.studio.thegraph.com/query/28985/testing-ground/c3BytesId

Use `Bytes` for C3RetireRequest `id`

---

polygon-digital-carbon/schema.graphql
polygon-digital-carbon/src/RetirementHandler.ts
polygon-digital-carbon/src/templates/C3ProjectTokenFactory.ts
polygon-digital-carbon/subgraph.template.yaml
polygon-digital-carbon/subgraph.yaml

Previously used a blockHandler to check for tokenUris set after the project was minted.
Removed the blockHandler and using the event emitted by the set metadata function instead. This matches the tokenId in the event to the nft index in the `C3RetireRequest` to set the url in the event params.
test deployment: https://api.studio.thegraph.com/query/28985/digital-carbon-sandbox/VCUOMetadUpdated-handler

Handle `VCUOMetaDataUpdated` for C3 tokenURIs

---

polygon-digital-carbon/src/RetirementHandler.ts

Previously all retires were assumed to be valid if EndAsyncToken was emitted. However there is a success param in the event which is now tracked and will assign `FINALIZED` or `REVERTED` accordingly.

Handle reverted C3 finalizations for async retires

---

polygon-digital-carbon/schema.graphql
polygon-digital-carbon/src/MetadataHandler.ts
polygon-digital-carbon/src/RetirementHandler.ts
polygon-digital-carbon/subgraph.template.yaml
polygon-digital-carbon/subgraph.yaml
polygon-digital-carbon/utils/ipfs.ts

Implementing file data sources for c3 async retirement metadata.
Given the limitations of file data sources the ipfs data cannot be loaded into an on-chain handler.
However, the ipfs retirement data is now available on the `C3RetireRequest` entity, which will eliminate the need for extra ipfs calls in the api with the tokenURI.
Graft test: [Example Query](https://api.studio.thegraph.com/proxy/28985/testing-ground/fds-brain-working-again/graphql?query=query+MyQuery+%7B%0A++retire%28id%3A+%220x91eaab967a195d7b968269ca9d7282bdce65179a03000000%22%29+%7B%0A++++c3RetireRequest+%7B%0A++++++retirementMetadata+%7B%0A++++++++vintage%0A++++++++transferee%0A++++++++reason%0A++++++++projectId%0A++++++++projectAddress%0A++++++++pdf%0A++++++++owner%0A++++++++nftRegistry%0A++++++++image%0A++++++++id%0A+++ …

[`digital-carbon`]  Use file data sources for C3 async retirement metadata

---

polygon-digital-carbon/schema.graphql
polygon-digital-carbon/src/MetadataHandler.ts

The previous deployment attempted a conversion on `amount` that failed on the decimal value (0.001) which was passed in the most recent retirement. Originally eco was supposed to be whole tonne retirements only which is where the break entered.
In this PR amount is just handled as a string to account for all cases.

[`digital-carbon`] Fix amount handling in c3RetirementMetadata

---

carbonmark/src/Projects.ts
lib/utils/EcoRegistryProjectInfo.ts
polygon-digital-carbon/src/utils/CarbonCredit.ts
polygon-digital-carbon/src/utils/CarbonProject.ts

The on-chain name and category isn't reliable for c3 projects yet. 
This is a temporary fix to add c3 projects for name and category info. Normally this wouldn't matter and would be fetched from the cms, however in the frontend there is still a direct subgraph call where these attributes are needed.

[`digital-carbon`] Add ECO projects to lib/

---

polygon-digital-carbon/schema.graphql
polygon-digital-carbon/src/RetirementHandler.ts
polygon-digital-carbon/src/TransferHandler.ts
polygon-digital-carbon/src/utils/AsyncRetireRequest.ts
polygon-digital-carbon/src/utils/C3.ts
polygon-digital-carbon/src/utils/Toucan.ts
polygon-digital-carbon/utils/enums.ts
polygon-digital-carbon/utils/getRetirementsContractAddress.ts

This PR combines the `ToucanBridgeRequest` and `C3RetireRequest` into one entity `AsyncRetireRequest`. 
Any registry specific fields that aren't required for other async requests are saved in their own entity on `AsyncRetireRequest`.

[`digital-carbon`] Combine async retire entities

---

polygon-digital-carbon/schema.graphql
polygon-digital-carbon/src/utils/CarbonCredit.ts

Adding a field for `batchSuffix` to the schema and populating it only for J-credits.
While it'd be possible to add `credit.creditId` field, different registries would require different `creditId` constructions:
JCS: JCS + (`registryProjectId`+`batchSuffix`) + `vintage`
ICR: ICR + `registryProjectId` + `vintage` + `tokenId`
Verra: `registry` + `registryProjectId` + `vintage` i.e. current format
Therefore the Credit class would still be needed to parse the different constructions. It's more straightforward at this stage to just add the batchSuffix which the Credit class already handles.
Although the JCS suffix is named batchId in the Credit class, it is named batchSuffix here to not confuse with batch token(*) ids.

[`digital-carbon`] Add batchSuffix for J-credit

---

polygon-bridged-carbon/src/utils/Constants.ts
polygon-bridged-carbon/src/utils/Token.ts
polygon-bridged-carbon/src/utils/pool_token/PoolTokenFactory.ts
polygon-bridged-carbon/src/utils/pool_token/impl/CCO2.ts

The absence of cco2 is breaking the sync as the subgraph is indexing the CarbonRetired event but doesn't have the cco2 token address available.

[`polygon-bridged-carbon`] Add CCO2 token contract address

---

.github/workflows/deploy.yaml

Add ethereum bridged carbon to alchemy as it is now used in the api

Actions: add ethereum bridged carbon to alchemy deployments

---

carbonmark/src/Carbonmark.ts
carbonmark/src/Entities.ts

feat: explicitly set node 16 and back to octokit

explicitly set node 16 and back to octokit

---

.github/workflows/ci.yaml

Matchstick does not run in linux; we need to add the -d flag so the tests will run in docker in the gha.
Also required a bump to node v18 in ci.yaml to enable the docker flag.
deply and dev-deploy are still using 16, for consistency those should be increased as well.

[`GHA`] Added -d flag for ci.yaml tests and increase node -v to 18

---

.github/workflows/deploy.yaml

We should only deploy to alchemy for a main merge to avoid bloating the alchemy entity count ($).
chore: only alchemy deployments from main merge

[`GHA`] Only deploy to Alchemy on a main merge

---

.github/workflows/deploy.yaml

the octokit installation was causing the commit error, removed as it is already in the root dependencies.  Also added subgraph.yaml to the commits as we are using prepare-matic for pdc and carbonmark.
I tested with a mock main and staging, minus the deployment steps, and all worked correctly.  
There might be some phantom tags to be worked out with the initiation logic of subgraphs that don't already have tags. I'll handle with a follow-up PR though, mainly wanted to unblock the DCI deployments.
The main
fix: gha deploy

[`GHA`] Remove octokit dependency & commit subgraph.yaml

---

.github/workflows/deploy.yaml

added a new token (which needs to be added to gh) ALL_PERMISSIONS_TOKEN that will allow the gha commits and tags to occur.
chore: add ALL_PERMISSIONS_TOKEN

[`gha`] add `ALL_PERMISSIONS_TOKEN` for gha commits

---

.github/workflows/ci.yaml
carbonmark/package.json
carbonmark/schema.graphql
carbonmark/src/Carbonmark.ts
carbonmark/src/CreditManager.ts
carbonmark/src/Entities.ts
carbonmark/tests/CreditManager.test.ts
carbonmark/version.json

When the `CreditManager` is used the project with the correct id (`registry-registryId-vintage`) is correctly added to the store. 
However when listings are created the hardcoded `PROJECT_INFO` is still used as the source of truth, not the store directly, so any projects added via CreditManager are not available.
Additionally, when a listing is created only the tokenAddress and tokenId are emitted, so we can't directly load the Project entity (`registry-registryId-vintage`) created by the CreditManager as it will not be in the `PROJECT_INFO` list. 
In order to load the Project entity and not change the Project entity's id, this PR introduces a ProjectByToken entity so we can save that entity on a CreditManager update and use it in `loadOrCreateProject` when creating a listing.
feat: …

[`Carbonmark`] Intermediate `ProjectByToken` entity

---

.github/workflows/deploy-dev.yaml
.github/workflows/deploy.yaml

This flag was deprecated in 0.88.0
https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/CHANGELOG.md#0880
I will create an issue as we still need to remove useage of `--product` flag from our package.json commands, I am just not sure what the replacement is yet.

remove --studio flag from deploy CI
